# Generated by Django 3.0.8 on 2022-03-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0038_raiseticket_raised_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiseticket',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=50, null=True),
        ),
    ]
