# Generated by Django 3.0.8 on 2022-03-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0042_auto_20220328_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiseticket',
            name='Type',
            field=models.CharField(blank=True, choices=[('Query', 'Query'), ('Suggestion', 'Suggestion'), ('Complaint', 'Complaint')], default=('Query', 'Query'), max_length=50, null=True),
        ),
    ]
