# Generated by Django 3.0.8 on 2022-05-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0047_auto_20220329_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='category',
            field=models.CharField(choices=[('CNM', 'CNM'), ('CNM58', 'CNM58'), ('ULTRACON', 'ULTRACON'), ('TECH58', 'TECH58'), ('HR58', 'HR58')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='automation',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ticket/'),
        ),
        migrations.AddField(
            model_name='automation',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='automation',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automation',
            name='subcategory',
            field=models.CharField(choices=[('CNM', 'CNM'), ('CNM58', 'CNM58'), ('ULTRACON', 'ULTRACON'), ('TECH58', 'TECH58'), ('HR58', 'HR58')], max_length=50, null=True),
        ),
    ]
