# Generated by Django 3.0.8 on 2022-05-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0048_auto_20220511_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='Type',
            field=models.CharField(blank=True, choices=[('Query', 'Query'), ('Suggestion', 'Suggestion'), ('Complaint', 'Complaint')], default=('Query', 'Query'), max_length=50, null=True),
        ),
    ]
